Act.create(name: "New York Yankees", description: "The New York Yankees are an American professional baseball team based in the Bronx, New York City, New York, that competes in Major League Baseball (MLB). The Yankees are a member of MLB's American League (AL) East division. ", size: "40", location: "New York, NY", website: "http://www.yankees.com/") #3
Act.create(name: "The Rockettes", description: "The Rockettes are a precision dance company. Founded in 1925 in St. Louis, Missouri, since 1932 they have performed at Radio City Music Hall in Manhattan, New York City. During the Christmas season, the Rockettes present five shows a day, seven days a week. Perhaps their best-known routine is an eye-high leg kick in perfect unison in a chorus line, which they include at the end of every performance.", size: "30", location: "New York, NY", website: "https://www.rockettes.com" ) #4
Act.create(name: "New York Philharmonic", description: "New York Philharmonic-Symphony Orchestra is a symphony orchestra based in New York City in the United States. It is one of the leading American orchestras popularly referred to as the Big Five. The Philharmonic's home is David Geffen Hall, formerly known as Avery Fisher Hall until September 2015, located in New York's Lincoln Center for the Performing Arts.ts record-setting 14,000th concert was given in December 2004.", size: "50", location: "New York, NY", website: "http://www.nyphil.org/") #5
Act.create(name: "Billy Joel", description: "
The internationally acclaimed, six time Grammy-winning New Yorker has a decades-long history with the Garden starting with his first concert in 1978. In 2014, Billy Joel was established as the first-ever music franchise at Madison Square Garden - joining the Knicks, Rangers and Liberty as a resident at the World’s Most Famous Arena with a string of 12 sold out shows.  He’s now set to break the record of “the longest run of any artist” with a 13th consecutive show in January 2014, which will also mark his 59th show at The Garden.", size: "5", location: "New York, NY", website: "http://www.billyjoel.com/") #6
Venue.create(name: "Yankee Stadium", address: "1 E 161st St,", city: "New York", state: "NY", zipcode: "10451", phone: "(718) 293-4300", email: "yankees@mlb.com", website: "http://newyork.yankees.mlb.com") #2
Venue.create(name: "Radio City Music Hall", address: "1260 Ave of the Americas", city: "New York", state: "NY", zipcode: "10020", phone: "(212) 465-6741", email: "radiocity@msg.com", website: "http://radiocity.com") #3
Venue.create(name: "Lincoln Center for the Performing Arts", address: "10 Lincoln Center Plaza", city: "New York", state: "NY", zipcode: "10023", phone: "(212) 875-5456", email: "info@aboutlincolncenter.org", website: "http://lincolncenter.org") #4
Venue.create(name: "Madison Square Garden", address: "4 Pennsylvania Plaza Plaza", city: "New York", state: "NY", zipcode: "10001", phone: "(212) 465-6471", email: "msgfeedback@msg.com", website: "http://wwww.thegarden.com") #5
Venue.create(name: "The Beacon Theatre", address: "2124 Broadway", city: "New York", state: "NY", zipcode: "10023", phone: "(212) 465-6500", email: "feedback@beacontheatrenyc.com", website: "http://www.beacontheatre.com") #6
